# Generated by Django 4.2.1 on 2023-05-07 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_o', models.CharField(max_length=5)),
                ('nom_o', models.CharField(max_length=20)),
                ('fec_o', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_p', models.CharField(max_length=4)),
                ('doc_p', models.CharField(max_length=9, validators=[myapp.models.only_int])),
                ('ape_p', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'El campo debe contener solo letras.')])),
                ('nom_p', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'El campo debe contener solo letras.')])),
                ('tel_p', models.CharField(max_length=12, validators=[myapp.models.only_int])),
                ('direc', models.CharField(max_length=30)),
                ('dep', models.CharField(max_length=3, validators=[myapp.models.only_int])),
                ('sal', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_d', models.CharField(max_length=25)),
                ('cod_d', models.CharField(max_length=3)),
                ('codper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.persona')),
            ],
        ),
    ]
