# Generated by Django 4.2.1 on 2023-05-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_dependencia_codper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='codper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.persona'),
        ),
    ]
