# Generated by Django 4.2.1 on 2023-05-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_dependencia_codper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='codper',
            field=models.CharField(max_length=4),
        ),
    ]
