# Generated by Django 4.2.1 on 2023-05-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_dependencia_codper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencia',
            old_name='cod_d',
            new_name='codigo_dependencia',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='codper',
            new_name='codigo_jefe',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='nom_d',
            new_name='nombre_dependencia',
        ),
        migrations.RenameField(
            model_name='organigrama',
            old_name='cod_o',
            new_name='codigo_organigrama',
        ),
        migrations.RenameField(
            model_name='organigrama',
            old_name='fec_o',
            new_name='fecha_organigrama',
        ),
        migrations.RenameField(
            model_name='organigrama',
            old_name='nom_o',
            new_name='nombre_organigrama',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='ape_p',
            new_name='apellido_persona',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='cod_p',
            new_name='codigo_persona',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='dep',
            new_name='dependencia',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='direc',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='doc_p',
            new_name='documento_persona',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nom_p',
            new_name='nombre_persona',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='sal',
            new_name='salario',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='tel_p',
            new_name='telofono_persona',
        ),
    ]
