# Generated by Django 4.2.1 on 2023-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_cod_d_dependencia_codigo_dependencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='eliminar',
            field=models.BooleanField(default=False),
        ),
    ]
