# Generated by Django 4.2.1 on 2023-05-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_dependencia_eliminar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencia',
            name='eliminar',
        ),
        migrations.AlterField(
            model_name='organigrama',
            name='fecha_organigrama',
            field=models.DateField(auto_now_add=True),
        ),
    ]
